// <auto-generated />
namespace PharmacyStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitPharmacy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitPharmacy));
        
        string IMigrationMetadata.Id
        {
            get { return "202511031744046_InitPharmacy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
